<?php

namespace Gandalflebleu\Rbac\Controller;

use Laminas\Mvc\Controller\AbstractActionController;
use Laminas\Mvc\MvcEvent;
use Laminas\View\Helper\ViewModel;
use PHPUnit\Util\Exception;

class AccessDeniedController extends AbstractActionController
{
    public function onDispatch(MvcEvent $e)
    {
        $e->getResponse()->setStatusCode(403);
        return parent::onDispatch($e); // TODO: Change the autogenerated stub
    }

    public function indexAction(): ViewModel
    {
        return new ViewModel();
    }

}