<div class="card border-primary mb-3" style="max-width: 20rem;">
    <div class="card-header">Authentification</div>
    <div class="card-body">
        <?= $this->form()->openTag($this->form);; ?>
        <div class="form-group">
            <label for="login" class="form-label mt-4"><?= $this->formLabel($this->form->get('login')); ?></label>
            <?= $this->formElement($this->form->get('login')); ?>
            <small><?= $this->formElementErrors($this->form->get('login')); ?></small>
        </div>
        <div class="form-group">
            <label for="login" class="form-label mt-4"><?= $this->formLabel($this->form->get('password')); ?></label>
            <?= $this->formElement($this->form->get('password')); ?>
            <small><?= $this->formElementErrors($this->form->get('password')); ?></small>
        </div>

        <div class="form-group">
            <label for="login" class="form-label mt-4"><?= $this->formLabel($this->form->get('remember_me')); ?></label>
            <?= $this->formElement($this->form->get('remember_me')); ?>
            <small><?= $this->formElementErrors($this->form->get('remember_me')); ?></small>
        </div>

        <?= $this->formElement($this->form->get('csrf')); ?>
        <?= $this->formElementErrors($this->form->get('csrf')); ?>
        <?= $this->formElement($this->form->get('submit')); ?>
        <?= $this->form()->closeTag(); ?>
        <small>Not already registered <a href="<?= $this->url('log', ['action'=>'signup']) ?>">Create account</a></small>
    </div>
    <?php if($this->error): ?>
        <div class="alert alert-dismissible alert-warning">
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            <h4 class="alert-heading">Something went wrong!</h4>
            <p class="mb-0">code: <?= $this->error->getCode() ?>, <?= $this->error->getMessage(); ?></p>
        </div>
    <?php endif; ?>
</div>
